baseURL = 'https://khoancatbetong.com/'
languageCode = 'vi'
defaultContentLanguage = 'vi'
title = 'Khó ăn cát bê tông'
theme = 'mainroad'

[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.vi]
    languageCode = 'vi'
    languageDirection = 'ltr'
    languageName = 'Vietnamese'
    weight = 1

[Params.logo]
  subtitle = "Hướng dẫn làm Web từ số không" # Logo subtitle
  image = "img/logo.png"

[menus]
  [[menus.main]]
    name = 'Trang nhà'
    url = '/'
    weight = 10
  [[menus.main]]
    name = 'Web căn bản'
    url = '/web'
    weight = 20
  [[menus.main]]
    name = 'WordPress'
    url = '/wp'
    weight = 30
  [[menus.main]]
    name = 'Blog'
    url = '/blog'
    weight = 40
  [[menus.footer]]
    name = 'Điều khoản và điều kiện'
    url = '/dieu-khoan'
    weight = 10
  [[menus.footer]]
    name = 'Chính sách bảo mật'
    url = '/chinh-sach'
    weight = 20